title: Ricardo Martins
description: Universidade de Coimbra
baseurl: ""
url: https://ricardomar.github.io

theme: jekyll-nagymaros

indexing: true

permalink: pretty

language_id: en

exclude:
  - LICENSE
  - README.md
