title: Escola de Verão CIBIT-ICNAS
description: Universidade de Coimbra
baseurl: ""
url: https://ricardomar.github.io/

theme: jekyll-nagymaros

indexing: true

permalink: pretty

language_id: pt-PT

exclude:
  - LICENSE
  - README.md
