title: Nagymaros
description: Jekyll theme for a conference website
baseurl: "/demo"
url: 

theme: jekyll-nagymaros

copyright: Place Holder
indexing: false

permalink: pretty

exclude:
  - LICENSE
  - README.md
