title: Nagymaros
description: Jekyll theme for a conference website
baseurl: ""
url: https://ricardomar.github.io/demo

theme: jekyll-nagymaros

copyright: Place Holder
indexing: false

permalink: pretty

exclude:
  - LICENSE
  - README.md
